version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: booking-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
