services:
  postgres-db:
    image: postgres:latest
    container_name: booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MeetingRoom
    ports:
      - "5432:5432"
    volumes:
      - docker_pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  docker_pgdata: